services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://proyecto-test-1-backend.onrender.com
